//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0", IsNullable=false)]
    public partial class produktyLecznicze {
        
        private produktLeczniczyMT[] produktLeczniczyField;
        
        private string stanNaDzienField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("produktLeczniczy")]
        public produktLeczniczyMT[] produktLeczniczy {
            get {
                return this.produktLeczniczyField;
            }
            set {
                this.produktLeczniczyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stanNaDzien {
            get {
                return this.stanNaDzienField;
            }
            set {
                this.stanNaDzienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0")]
    public partial class produktLeczniczyMT {
        
        private string[] substancjeCzynneField;
        
        private opakowanieMT[] opakowaniaField;
        
        private substancjaMT[] substancjeField;
        
        private gatunekMT[] gatunkiField;
        
        private string nazwaProduktuField;
        
        private string idProduktuField;
        
        private string rodzajPreparatuField;
        
        private string nazwaPowszechnieStosowanaField;
        
        private string mocField;
        
        private string postacField;
        
        private string podmiotOdpowiedzielnyField;
        
        private produktLeczniczyMTTypProcedury typProceduryField;
        
        private bool typProceduryFieldSpecified;
        
        private string numerPozwoleniaField;
        
        private string waznoscPozwoleniaField;
        
        private string kodATCField;
        
        private string gatunkiDoceloweField;
        
        private string idField;
        
        private string okresyKarencjiField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("substancjaCzynna", IsNullable=false)]
        public string[] substancjeCzynne {
            get {
                return this.substancjeCzynneField;
            }
            set {
                this.substancjeCzynneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("opakowanie", IsNullable=false)]
        public opakowanieMT[] opakowania {
            get {
                return this.opakowaniaField;
            }
            set {
                this.opakowaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("substancja", IsNullable=false)]
        public substancjaMT[] substancje {
            get {
                return this.substancjeField;
            }
            set {
                this.substancjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("gatunek", IsNullable=false)]
        public gatunekMT[] gatunki {
            get {
                return this.gatunkiField;
            }
            set {
                this.gatunkiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazwaProduktu {
            get {
                return this.nazwaProduktuField;
            }
            set {
                this.nazwaProduktuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idProduktu {
            get {
                return this.idProduktuField;
            }
            set {
                this.idProduktuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rodzajPreparatu {
            get {
                return this.rodzajPreparatuField;
            }
            set {
                this.rodzajPreparatuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazwaPowszechnieStosowana {
            get {
                return this.nazwaPowszechnieStosowanaField;
            }
            set {
                this.nazwaPowszechnieStosowanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string moc {
            get {
                return this.mocField;
            }
            set {
                this.mocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string postac {
            get {
                return this.postacField;
            }
            set {
                this.postacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string podmiotOdpowiedzielny {
            get {
                return this.podmiotOdpowiedzielnyField;
            }
            set {
                this.podmiotOdpowiedzielnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public produktLeczniczyMTTypProcedury typProcedury {
            get {
                return this.typProceduryField;
            }
            set {
                this.typProceduryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typProcedurySpecified {
            get {
                return this.typProceduryFieldSpecified;
            }
            set {
                this.typProceduryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string numerPozwolenia {
            get {
                return this.numerPozwoleniaField;
            }
            set {
                this.numerPozwoleniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string waznoscPozwolenia {
            get {
                return this.waznoscPozwoleniaField;
            }
            set {
                this.waznoscPozwoleniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kodATC {
            get {
                return this.kodATCField;
            }
            set {
                this.kodATCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gatunkiDocelowe {
            get {
                return this.gatunkiDoceloweField;
            }
            set {
                this.gatunkiDoceloweField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string okresyKarencji {
            get {
                return this.okresyKarencjiField;
            }
            set {
                this.okresyKarencjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0")]
    public partial class opakowanieMT {
        
        private string idField;
        
        private string wielkoscField;
        
        private string jednostkaWielkosciField;
        
        private string kodEANField;
        
        private opakowanieMTKategoriaDostepnosci kategoriaDostepnosciField;
        
        private bool kategoriaDostepnosciFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string wielkosc {
            get {
                return this.wielkoscField;
            }
            set {
                this.wielkoscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string jednostkaWielkosci {
            get {
                return this.jednostkaWielkosciField;
            }
            set {
                this.jednostkaWielkosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kodEAN {
            get {
                return this.kodEANField;
            }
            set {
                this.kodEANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public opakowanieMTKategoriaDostepnosci kategoriaDostepnosci {
            get {
                return this.kategoriaDostepnosciField;
            }
            set {
                this.kategoriaDostepnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kategoriaDostepnosciSpecified {
            get {
                return this.kategoriaDostepnosciFieldSpecified;
            }
            set {
                this.kategoriaDostepnosciFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0")]
    public enum opakowanieMTKategoriaDostepnosci {
        
        /// <remarks/>
        OTC,
        
        /// <remarks/>
        Rpw,
        
        /// <remarks/>
        Lz,
        
        /// <remarks/>
        Rp,
        
        /// <remarks/>
        Rpz,
        
        /// <remarks/>
        BRAK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0")]
    public partial class gatunekMT {
        
        private string nazwaGatunkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazwaGatunku {
            get {
                return this.nazwaGatunkuField;
            }
            set {
                this.nazwaGatunkuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0")]
    public partial class substancjaMT {
        
        private string nazwaSubstancjiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nazwaSubstancji {
            get {
                return this.nazwaSubstancjiField;
            }
            set {
                this.nazwaSubstancjiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rejestrymedyczne.csioz.gov.pl/rpl/eksport-danych-v1.0")]
    public enum produktLeczniczyMTTypProcedury {
        
        /// <remarks/>
        NAR,
        
        /// <remarks/>
        DCP,
        
        /// <remarks/>
        CEN,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        MRP,
    }
}
